jobs:
- template: templates/linux-ci.yml
  parameters:
    AgentPool : 'Linux-CPU'
    JobName: 'Linux_CI_Dev'
    BuildCommand: 'tools/ci_build/github/linux/run_dockerbuild.sh -o ubuntu16.04 -d cpu -r $(Build.BinariesDirectory) -x "--disable_contrib_ops  --disable_ml_ops"'
    DoNugetPack:  'false'
    ArtifactName: 'drop-linux'
    TimeoutInMinutes: 120
    # Enable unreleased onnx opsets in CI builds
    # This facilitates testing the implementation for the new opsets
    AllowReleasedOpsetOnly: '0'
